baseUrl:
  #  es: http://localhost:9200
  es: localhost:9200

app:
  services:
    ext-ui: http://localhost:8081
  user-groups:
    default-group: "NEED_HELP_CLIENT"
    admin-group: "NEED_HELP_ADMIN"
  credentials:
    phone: 12345
    password: 12345
  allowed-file-extension:
    - jpg
    - png

file:
  storage:
    endpoint: http://localhost:9000
    port: 9000
    accessKey: TMOmHBBwZzXpjRVq
    secretKey: awi6dzSfPbARMUli23uQN66z8EUyvan6
    secure: false
    bucket-name: flux-test-market-2022
    image-size: 10485760
    file-size: 1073741824


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB